### ISSUE TITLE
Boolean array

### ISSUE THREAD

**Issue by jeffpyke** [manifoldco/swagger-to-ts#195]
With this swagger 2.0 schema:
```
MyObject:
  properties:
    myArray:
      type: "array"
      items:
        type: "boolean"
```
I am seeing this typescript output.
```
export interface MyObject {
  myArray?: MyObjectMyArray[];
}
export interface MyObjectMyArray {}
```
Expected output:
```
export interface MyObject {
  myArray?: boolean[];
}
```
Is this a known issue? Thanks in advance.
